/* IS_AUTOGENERATED_SO_ALLOW_AUTODELETE=YES */
/* The previous line is to allow auto deletion */

#import <Foundation/Foundation.h>
#import <Foundation/NSString.h>
#import "libGolgi.h"



@interface QuakeFilter : NSObject
{
    NSString *golgiId;
    BOOL golgiIdIsSet;
    double lat;
    BOOL latIsSet;
    double lng;
    BOOL lngIsSet;
    double radius;
    BOOL radiusIsSet;
}

@property (readonly) BOOL golgiIdIsSet;
- (NSString *)getGolgiId;
- (void)setGolgiId:(NSString *)golgiId;
@property (readonly) BOOL latIsSet;
- (double)getLat;
- (void)setLat:(double )lat;
@property (readonly) BOOL lngIsSet;
- (double)getLng;
- (void)setLng:(double )lng;
@property (readonly) BOOL radiusIsSet;
- (double)getRadius;
- (void)setRadius:(double )radius;

+ (QuakeFilter *)deserialiseFromString: (NSString *)string;
+ (QuakeFilter *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface QuakeDetails : NSObject
{
    double mag;
    BOOL magIsSet;
    double lat;
    BOOL latIsSet;
    double lng;
    BOOL lngIsSet;
    NSString *title;
    BOOL titleIsSet;
    NSInteger timestamp;
    BOOL timestampIsSet;
}

@property (readonly) BOOL magIsSet;
- (double)getMag;
- (void)setMag:(double )mag;
@property (readonly) BOOL latIsSet;
- (double)getLat;
- (void)setLat:(double )lat;
@property (readonly) BOOL lngIsSet;
- (double)getLng;
- (void)setLng:(double )lng;
@property (readonly) BOOL titleIsSet;
- (NSString *)getTitle;
- (void)setTitle:(NSString *)title;
@property (readonly) BOOL timestampIsSet;
- (NSInteger)getTimestamp;
- (void)setTimestamp:(NSInteger )timestamp;

+ (QuakeDetails *)deserialiseFromString: (NSString *)string;
+ (QuakeDetails *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface QuakeWatch_addMe_reqArg : NSObject
{
    QuakeFilter *filter;
    BOOL filterIsSet;
}

@property (readonly) BOOL filterIsSet;
- (QuakeFilter *)getFilter;
- (void)setFilter:(QuakeFilter *)filter;

+ (QuakeWatch_addMe_reqArg *)deserialiseFromString: (NSString *)string;
+ (QuakeWatch_addMe_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface QuakeWatch_addMe_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (QuakeWatch_addMe_rspArg *)deserialiseFromString: (NSString *)string;
+ (QuakeWatch_addMe_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface QuakeWatch_removeMe_reqArg : NSObject
{
    NSString *golgiId;
    BOOL golgiIdIsSet;
}

@property (readonly) BOOL golgiIdIsSet;
- (NSString *)getGolgiId;
- (void)setGolgiId:(NSString *)golgiId;

+ (QuakeWatch_removeMe_reqArg *)deserialiseFromString: (NSString *)string;
+ (QuakeWatch_removeMe_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface QuakeWatch_removeMe_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (QuakeWatch_removeMe_rspArg *)deserialiseFromString: (NSString *)string;
+ (QuakeWatch_removeMe_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface QuakeWatch_quakeAlert_reqArg : NSObject
{
    QuakeDetails *details;
    BOOL detailsIsSet;
}

@property (readonly) BOOL detailsIsSet;
- (QuakeDetails *)getDetails;
- (void)setDetails:(QuakeDetails *)details;

+ (QuakeWatch_quakeAlert_reqArg *)deserialiseFromString: (NSString *)string;
+ (QuakeWatch_quakeAlert_reqArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end


@interface QuakeWatch_quakeAlert_rspArg : NSObject
{
    NSInteger internalSuccess_;
    BOOL internalSuccess_IsSet;
    GolgiException *golgiException;
    BOOL golgiExceptionIsSet;
}

@property (readonly) BOOL internalSuccess_IsSet;
- (NSInteger)getInternalSuccess_;
- (void)setInternalSuccess_:(NSInteger )internalSuccess_;
@property (readonly) BOOL golgiExceptionIsSet;
- (GolgiException *)getGolgiException;
- (void)setGolgiException:(GolgiException *)golgiException;

+ (QuakeWatch_quakeAlert_rspArg *)deserialiseFromString: (NSString *)string;
+ (QuakeWatch_quakeAlert_rspArg *)deserialiseFromPayload: (GolgiPayload *)payload;
- (NSString *)serialiseWithPrefix:(NSString *)prefix;
- (NSString *)serialise;
- (id)initWithIsSet:(BOOL)defIsSet;
@end
//
// addMe
//
@protocol QuakeWatchAddMeResultSender
- (void)success;
@end
@protocol QuakeWatchAddMeResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol QuakeWatchAddMeRequestReceiver
- (void)addMeWithResultSender:(id<QuakeWatchAddMeResultSender>)resultSender andFilter:(QuakeFilter *)filter;
@end

//
// removeMe
//
@protocol QuakeWatchRemoveMeResultSender
- (void)success;
@end
@protocol QuakeWatchRemoveMeResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol QuakeWatchRemoveMeRequestReceiver
- (void)removeMeWithResultSender:(id<QuakeWatchRemoveMeResultSender>)resultSender andGolgiId:(NSString *)golgiId;
@end

//
// quakeAlert
//
@protocol QuakeWatchQuakeAlertResultSender
- (void)success;
@end
@protocol QuakeWatchQuakeAlertResultReceiver
- (void)success;
- (void)failureWithGolgiException:(GolgiException *)golgiException;
@end
@protocol QuakeWatchQuakeAlertRequestReceiver
- (void)quakeAlertWithResultSender:(id<QuakeWatchQuakeAlertResultSender>)resultSender andDetails:(QuakeDetails *)details;
@end

@interface QuakeWatchSvc : NSObject
+ (void)sendAddMeUsingResultReceiver:(id<QuakeWatchAddMeResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withFilter:(QuakeFilter *)filter;
+ (void)sendAddMeUsingResultReceiver:(id<QuakeWatchAddMeResultReceiver>)resultReceiver andDestination:(NSString *)_dst withFilter:(QuakeFilter *)filter;
+ (void)registerAddMeRequestReceiver:(id<QuakeWatchAddMeRequestReceiver>)requestReceiver;

+ (void)sendRemoveMeUsingResultReceiver:(id<QuakeWatchRemoveMeResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId;
+ (void)sendRemoveMeUsingResultReceiver:(id<QuakeWatchRemoveMeResultReceiver>)resultReceiver andDestination:(NSString *)_dst withGolgiId:(NSString *)golgiId;
+ (void)registerRemoveMeRequestReceiver:(id<QuakeWatchRemoveMeRequestReceiver>)requestReceiver;

+ (void)sendQuakeAlertUsingResultReceiver:(id<QuakeWatchQuakeAlertResultReceiver>)resultReceiver withTransportOptions:(GolgiTransportOptions *)options andDestination:(NSString *)_dst withDetails:(QuakeDetails *)details;
+ (void)sendQuakeAlertUsingResultReceiver:(id<QuakeWatchQuakeAlertResultReceiver>)resultReceiver andDestination:(NSString *)_dst withDetails:(QuakeDetails *)details;
+ (void)registerQuakeAlertRequestReceiver:(id<QuakeWatchQuakeAlertRequestReceiver>)requestReceiver;

@end
